### Request 1
POST  http://localhost/Aikon/server/Register.php
Content-Type: application/json

{
  "userName": "test11",
  "password": "test11",
  "userEmail": "test11@gmail.com"
}

###
POST  http://localhost/Aikon/server/TestLogin.php
Content-Type: application/json

{
  "userEmail": "rapha3@gmail.com",
  "password": "rapha3"
}